version: '2.0'
services: 
    aida:
        build: .
        volumes: ['./src:/usr/src/aida', './data:/usr/src/app/data']
        command: bash -c "gunicorn serve:app --log-file=- -b 0.0.0.0:8000"
        ports: ["8000:8000"]
        environment:
            PYTHONPATH: /usr/src/app/models/research:/usr/src/app/models/research/slim